### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by ghost** [MyZuyx/SELF-XZIY#1]
saya logout di WhatsApp nya terus re run script nya.
terua ini muncul
![Uploading Screenshot_2021-08-21-02-20-44-943_com.termux.jpg…]()

SCRIPT WAS RUN WELL..
WARN [2021-08-20 19:20:38.655 +0000] (19634): connect attempt 1 failed: BaileysError: Unexpected error in login
    class: "Baileys"
    error: {
      "name": "BaileysError",
      "status": 401,
      "context": {
        "response": {
          "status": 401
        },
        "status": 401
      }
    }
(node:19634) UnhandledPromiseRejectionWarning: BaileysError: Unexpected error in login
    at WAConnection.authenticate (/data/data/com.termux/files/home/bot/node_modules/@adiwajshing/baileys/lib/WAConnection/1.Validation.js:97:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async WebSocket.<anonymous> (/data/data/com.termux/files/home/bot/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:107:40)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19634) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19634) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^Cstem tersambung... Connecting...
~/bot $

**Comment by MyZuyx** [comment]
Lu mau scan ulang trus eror? Mungkin sessions.json nya blom lu hapus kali bro
